/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fdams;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class fee1 extends javax.swing.JFrame {

    /**
     * Creates new form fee
     */
    public fee1() {
        initComponents();
    }
    
     String corse,dura,cors;
    //int dura;
      int i=1;
     public fee1(String course,String dur,String cor) {
         
        initComponents();
        this.corse=course;
        this.cors=cor;
        setcourse1.setText(cor);
        setduration.setText(dur);
        int ndur=Integer.parseInt(dur);
        while(ndur>0)
        {
        //String temp=Integer.toString(this.i);   
        this.i++;    
        ndur--;
        }
        year.addItem("1");
        year.setSelectedItem("1");
        this.i--;
    }
     
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        setduration = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        setcourse1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        admission = new javax.swing.JTextField();
        tuition = new javax.swing.JTextField();
        soft = new javax.swing.JTextField();
        industrial = new javax.swing.JTextField();
        university = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        internal = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        course = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("Duration :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, -1, -1));

        setduration.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setduration.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(setduration, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, 60, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("P.O, Shimla Bypass Road Shiniwala, Sherpur, Uttarakhand 248197, Phone: 099971 55111");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, 10));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 31)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("College Of Engineering");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Shivalik");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 255, 255));
        jLabel11.setText("TOTAL :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 710, -1, 40));

        setcourse1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setcourse1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(setcourse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 110, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 780, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 255, 255));
        jLabel12.setText("Year :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 255, 255));
        jLabel13.setText("Admission fees :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, 30));

        jPanel2.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 90, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 255, 255));
        jLabel14.setText("Course :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 255, 255));
        jLabel15.setText("Tuition fees :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 255, 255));
        jLabel16.setText("Soft skill training :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 255, 255));
        jLabel17.setText("Industrial training :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, -1, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 255, 255));
        jLabel18.setText("University fees :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, -1, 20));

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel2.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 710, 170, 30));

        admission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admissionActionPerformed(evt);
            }
        });
        jPanel2.add(admission, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 170, 30));

        tuition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuitionActionPerformed(evt);
            }
        });
        jPanel2.add(tuition, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 170, 30));

        soft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                softActionPerformed(evt);
            }
        });
        jPanel2.add(soft, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 170, 30));

        industrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                industrialActionPerformed(evt);
            }
        });
        jPanel2.add(industrial, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, 170, 30));

        university.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                universityActionPerformed(evt);
            }
        });
        jPanel2.add(university, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 550, 170, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 680, 200, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 255, 255));
        jLabel19.setText("Internal examination fees :");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, -1, 30));

        internal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                internalFocusLost(evt);
            }
        });
        internal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internalActionPerformed(evt);
            }
        });
        jPanel2.add(internal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 610, 170, 30));

        add.setBackground(new java.awt.Color(51, 0, 51));
        add.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/add2.png"))); // NOI18N
        add.setText(" Add");
        add.setBorder(null);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 732, 120, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 1050, 820));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/home.png"))); // NOI18N
        jLabel1.setText("  HOME");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 170, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 290, 80));

        course.setBackground(new java.awt.Color(0, 51, 51));
        course.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        course.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                courseMouseMoved(evt);
            }
        });
        course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                courseMouseExited(evt);
            }
        });
        course.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/edit2.png"))); // NOI18N
        jLabel3.setText(" COURSES");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        course.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 170, 60));

        jPanel1.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 290, 80));

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/smallfee.png"))); // NOI18N
        jLabel4.setText(" FEE STRUCTURE");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 240, 80));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 290, 80));

        jPanel7.setBackground(new java.awt.Color(0, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/about.png"))); // NOI18N
        jLabel5.setText("   STUDENTS");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 210, 80));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 290, 80));

        jPanel9.setBackground(new java.awt.Color(0, 51, 51));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/logout.png"))); // NOI18N
        jLabel21.setText("  LOG OUT");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
        });
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 60));

        jPanel10.setBackground(new java.awt.Color(0, 51, 51));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/logout.png"))); // NOI18N
        jLabel22.setText("  LOG OUT");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 60));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 290, 80));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 290, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 820));

        setSize(new java.awt.Dimension(1466, 823));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void admissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admissionActionPerformed

    private void tuitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuitionActionPerformed

    private void softActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_softActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_softActionPerformed

    private void industrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_industrialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_industrialActionPerformed

    private void universityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_universityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_universityActionPerformed

    private void internalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internalActionPerformed

     boolean isValid(String space) {
     String ePattern = ".*[^ ].*";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(space);
           return m.matches();
   }
    
     boolean isValidNumber(String no) {
     String ePattern = "^[1-9]+[0-9]*$";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(no);
           return m.matches();
   }
    
    String ad,tu,so,in,un,inter;
    
    boolean isValidate()
    {
        ad=admission.getText();
        tu=tuition.getText();
        so=soft.getText();
        in=industrial.getText();
        un=university.getText();
        inter=internal.getText();
    
        if(ad.equals("") || tu.equals("") || so.equals("") || in.equals("") || un.equals("") || inter.equals(""))
        {
         JOptionPane.showMessageDialog(this,"All fields are required");
         return false;
        }
        else if(!isValid(ad) || !isValid(tu) || !isValid(so) || !isValid(in) ||  !isValid(un) || !isValid(inter))
        {
         JOptionPane.showMessageDialog(this,"Spaces are not allowed!");
         return false;
        } 
        else if(!isValidNumber(ad) || !isValidNumber(tu) || !isValidNumber(so) || !isValidNumber(in) ||  !isValidNumber(un) || !isValidNumber(inter))
        {
         JOptionPane.showMessageDialog(this,"Only digits are allowed!");
         return false;
        }
    
    return true;
    
    }
    
    
    void totalFee(int total,String cor)
    {
    try
       {   
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/fdams","root","");
        String sql="update course set fee=? where courses=?";
        PreparedStatement stmt;
        stmt = conn.prepareStatement(sql);
        stmt.setInt(1,total);
        stmt.setString(2,cor);
        stmt.executeUpdate();
       }
       catch(HeadlessException | ClassNotFoundException | SQLException e)
       {
           e.printStackTrace();
       }
    
    
    }        
    
    int tl=0;
    void addFee(int j)
    {
    String selItem=(String)year.getSelectedItem();
    int no=Integer.parseInt(selItem);
    
    String n=Integer.toString(j);

    int tot=Integer.parseInt(ad)+Integer.parseInt(tu)+Integer.parseInt(so)+Integer.parseInt(in)+Integer.parseInt(un)+Integer.parseInt(inter);
    tl=tl+tot;
    if(!selItem.equals(n))
    {
    JOptionPane.showMessageDialog(this,"Please create previous year fee structure first");
    j--;
    }
    else 
    {
    try
       {   
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/fdams","root","");
        
          
        String sql="insert into "+cors+j+"(addmission_fee,tuition_fee,soft_skill_fee,industrial_training_fee,university_fee,internal_exam_fee,amount) values(?,?,?,?,?,?,?)";
        PreparedStatement stmt;
        stmt = conn.prepareStatement(sql);
        stmt.setInt(1,Integer.parseInt(ad));
        stmt.setInt(2,Integer.parseInt(tu));
        stmt.setInt(3,Integer.parseInt(so));
        stmt.setInt(4,Integer.parseInt(in));
        stmt.setInt(5,Integer.parseInt(un));
        stmt.setInt(6,Integer.parseInt(inter));
        stmt.setInt(7,tot);

        int get=stmt.executeUpdate();
        if(get>0)
        {    
        JOptionPane.showMessageDialog(this,"Fee structure for "+j+" year is created successsfully");
        total.setText("");
        admission.setText("");
        tuition.setText("");
        soft.setText("");
        industrial.setText("");
        university.setText("");
        internal.setText("");

        if(j!=i)
        {    
        String temp=Integer.toString(no+1); 
        year.addItem(temp);
        year.removeItem(selItem);
        year.setSelectedItem(Integer.toString(no+1));
        }
        }
        else 
        {
        JOptionPane.showMessageDialog(this,"Some technical glitch..try again!");
        }    
        if(j==i)
        {
        String sqli="update course set fee=?";
        PreparedStatement stmti;
        stmti = conn.prepareStatement(sqli);
        stmti.setInt(1,tl);
        stmti.executeUpdate();    
        JOptionPane.showMessageDialog(this,"New fee structure for "+cors+" has been created!");
        core cr=new core();
        cr.show();
        this.dispose();
        }    
       }
    
       catch(HeadlessException | ClassNotFoundException | SQLException e)
       {
           e.printStackTrace();
       }
      }
   
    }
    
    int count=0;
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        if(isValidate())
        {
        count++;
        addFee(count);
        }
        
    }//GEN-LAST:event_addActionPerformed

    private void internalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_internalFocusLost
        // TODO add your handling code here:
        
        if(isValidate())
        {
        int tot=Integer.parseInt(ad)+Integer.parseInt(tu)+Integer.parseInt(so)+Integer.parseInt(in)+Integer.parseInt(un)+Integer.parseInt(inter);
        total.setText(Integer.toString(tot));
        }    
    }//GEN-LAST:event_internalFocusLost

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        if(isValidate())
        {
        int tot=Integer.parseInt(ad)+Integer.parseInt(tu)+Integer.parseInt(so)+Integer.parseInt(in)+Integer.parseInt(un)+Integer.parseInt(inter);
        total.setText(Integer.toString(tot));
        } 
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        courses cv=new courses();
        cv.show();
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        Color col=new Color(105,105,105);
        jPanel3.setBackground(col);
        jPanel3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        Color col=new Color(0,51,51);
        jPanel3.setBackground(col);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        core c=new core();
        c.show();
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        Color col=new Color(105,105,105);
        course.setBackground(col);
        course.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        Color col=new Color(0,51,51);
        course.setBackground(col);
    }//GEN-LAST:event_jLabel3MouseExited

    private void courseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseMouseMoved
        // TODO add your handling code here:
        course.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        Color col=new Color(105,105,105);
        course.setBackground(col);

    }//GEN-LAST:event_courseMouseMoved

    private void courseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseMouseClicked
        // TODO add your handling code here:
        core cor=new core();
        cor.show();
        this.dispose();
    }//GEN-LAST:event_courseMouseClicked

    private void courseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseMouseExited
        // TODO add your handling code here:
        Color col=new Color(0,51,51);
        course.setBackground(col);
    }//GEN-LAST:event_courseMouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        feesearch fs=new feesearch();
        fs.show();
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        Color col=new Color(105,105,105);
        jPanel6.setBackground(col);
        jPanel6.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        Color col=new Color(0,51,51);
        jPanel6.setBackground(col);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        students stu=new students();
        stu.show();
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        Color col=new Color(105,105,105);
        jPanel7.setBackground(col);
        jPanel7.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        Color col=new Color(0,51,51);
        jPanel7.setBackground(col);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        login lg=new login();
        lg.show();
        this.dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseEntered
        // TODO add your handling code here:
        Color col=new Color(105,105,105);
        jPanel9.setBackground(col);
        jPanel9.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel21MouseEntered

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited
        // TODO add your handling code here:
        Color col=new Color(0,51,51);
        jPanel9.setBackground(col);
    }//GEN-LAST:event_jLabel21MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fee1().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField admission;
    private javax.swing.JPanel course;
    private javax.swing.JTextField industrial;
    private javax.swing.JTextField internal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel setcourse1;
    private javax.swing.JLabel setduration;
    private javax.swing.JTextField soft;
    private javax.swing.JTextField total;
    private javax.swing.JTextField tuition;
    private javax.swing.JTextField university;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
