/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fdams;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class feereceipt extends javax.swing.JFrame {

    /**
     * Creates new form feereceipt
     */
    public feereceipt() {
        initComponents();
    }
    
    String frst,lst,phon,co;
    int cur;
    public feereceipt(String fn,String ln,String ph,String crs,int cy,int p,int d) {
        initComponents();
        String g=gtId();
        rno.setText(g);
        received.setText(fn+" "+ln);
        phn.setText(ph);
        crse.setText(crs);
        yr.setText(Integer.toString(cy));
        cheque.hide();
        cbank.hide();
        ded.hide();
        db.hide();
        utr.hide();
        crb.hide();
        cq.hide();
        utrn.hide();
        utrb.hide();
        ddn.hide();
        ddb.hide();
        cbq.hide();
        this.frst=fn;
        this.lst=ln;
        this.phon=ph;
        this.co=crs;
        this.cur=cy;
    }
    
    
    
    String gtId()
    {
    int il=1;
    try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/fdams","root","");
        String sql="select * from feedetails order by id DESC LIMIT 1";
        PreparedStatement stmt;
        stmt = conn.prepareStatement(sql);
        ResultSet rs=stmt.executeQuery();
        if(rs.next())
            return Integer.toString(rs.getInt("id")+1);
    }
    catch(HeadlessException | ClassNotFoundException | SQLException e)
    {
    e.printStackTrace();
    }
    return Integer.toString(il);
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        fname = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        cr = new javax.swing.JLabel();
        cyr = new javax.swing.JLabel();
        paid = new javax.swing.JLabel();
        due = new javax.swing.JLabel();
        duratn = new javax.swing.JLabel();
        rno = new javax.swing.JLabel();
        r = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mode = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        ded = new javax.swing.JLabel();
        fr = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        received = new javax.swing.JLabel();
        phn = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        excess = new javax.swing.JTextField();
        ad = new javax.swing.JTextField();
        tu = new javax.swing.JTextField();
        so = new javax.swing.JTextField();
        in = new javax.swing.JTextField();
        un = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        internal = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        crse = new javax.swing.JLabel();
        yr = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        pd = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        bln = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        words = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        note = new javax.swing.JTextPane();
        jLabel44 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        crb = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dt = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        cbank = new javax.swing.JTextField();
        cheque = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        utr = new javax.swing.JLabel();
        cbq = new javax.swing.JLabel();
        db = new javax.swing.JLabel();
        cq = new javax.swing.JLabel();
        utrn = new javax.swing.JTextField();
        utrb = new javax.swing.JTextField();
        ddn = new javax.swing.JTextField();
        ddb = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        course = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        printfee = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fname.setForeground(new java.awt.Color(0, 102, 102));
        jPanel2.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        lname.setForeground(new java.awt.Color(0, 102, 102));
        jPanel2.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        phone.setForeground(new java.awt.Color(0, 102, 102));
        jPanel2.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        cr.setForeground(new java.awt.Color(0, 102, 102));
        jPanel2.add(cr, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        cyr.setForeground(new java.awt.Color(0, 102, 102));
        jPanel2.add(cyr, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));

        paid.setForeground(new java.awt.Color(0, 102, 102));
        jPanel2.add(paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, -1, -1));

        due.setForeground(new java.awt.Color(0, 102, 102));
        jPanel2.add(due, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, -1, -1));

        duratn.setForeground(new java.awt.Color(0, 102, 102));
        jPanel2.add(duratn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 130, -1, -1));

        rno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rno.setForeground(new java.awt.Color(153, 255, 255));
        rno.setText("1");
        jPanel2.add(rno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 40, 40));

        r.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        r.setText("SCE-");
        jPanel2.add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Receipt no :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        mode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Cheque", "DD", "NEFT" }));
        mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeActionPerformed(evt);
            }
        });
        jPanel2.add(mode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 110, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mode of Payment :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        ded.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ded.setForeground(new java.awt.Color(255, 255, 255));
        ded.setText("DD :");
        jPanel2.add(ded, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        fr.setBackground(new java.awt.Color(0, 102, 102));
        fr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frMouseClicked(evt);
            }
        });
        fr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("year");
        fr.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 70, 40, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Phone No :");
        fr.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Amount(in Rs)");
        fr.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, -1, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Received From :");
        fr.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        received.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        received.setText("Received From");
        fr.add(received, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        phn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phn.setText("Received From");
        fr.add(phn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));
        fr.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 510, 160, 20));
        fr.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 133, 890, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("S. No");
        fr.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, 40));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Signature");
        fr.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 1000, 200, 60));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Course :");
        fr.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 20));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Head");
        fr.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, 40));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("6");
        fr.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 30, 40));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("Tuition fee");
        fr.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, 40));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Soft Skill fee");
        fr.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, 40));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setText("Industrial Training");
        fr.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, 50));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("University fee");
        fr.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, 50));

        excess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excessActionPerformed(evt);
            }
        });
        fr.add(excess, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 630, 120, 30));
        fr.add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 120, -1));
        fr.add(tu, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 120, -1));
        fr.add(so, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 120, -1));
        fr.add(in, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 120, -1));
        fr.add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, 120, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setText("Admission fee");
        fr.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, 40));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setText("1");
        fr.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 30, 50));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setText("2");
        fr.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 30, 50));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setText("3");
        fr.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 30, 50));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setText("4");
        fr.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 30, 40));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setText("5");
        fr.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 30, 40));
        fr.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 890, 20));

        internal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                internalFocusLost(evt);
            }
        });
        fr.add(internal, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, 120, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setText("Internal examination fee");
        fr.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 210, 70));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Year :");
        fr.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 72, -1, 30));

        crse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        crse.setText("Received From");
        fr.add(crse, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        yr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fr.add(yr, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 72, -1, 30));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("Amount paid :");
        fr.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 210, 40));

        pd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdActionPerformed(evt);
            }
        });
        fr.add(pd, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 532, 120, 30));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel41.setText("Balance Amount to paid :");
        fr.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, 210, 50));

        bln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blnActionPerformed(evt);
            }
        });
        fr.add(bln, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 580, 120, 30));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Note : ");
        fr.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 750, 120, 30));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("Amount in words : ");
        fr.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 690, -1, 30));

        words.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordsActionPerformed(evt);
            }
        });
        fr.add(words, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 690, 700, 30));

        jScrollPane3.setViewportView(note);

        fr.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 732, 700, 70));

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel44.setText("Excess fee amount :");
        fr.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 620, 210, 50));
        fr.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 983, 110, 0));
        fr.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 1010, 160, 20));

        jPanel2.add(fr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1050, 1150));

        crb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        crb.setForeground(new java.awt.Color(255, 255, 255));
        crb.setText("Bank Name :");
        jPanel2.add(crb, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("27AAATLO123");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, -1, -1));
        jPanel2.add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 110, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Date :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, -1, -1));

        cbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbankActionPerformed(evt);
            }
        });
        jPanel2.add(cbank, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 390, -1));
        jPanel2.add(cheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 180, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("GSTIN :");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));

        utr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        utr.setForeground(new java.awt.Color(255, 255, 255));
        utr.setText("UTR No :");
        jPanel2.add(utr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        cbq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbq.setForeground(new java.awt.Color(255, 255, 255));
        cbq.setText("Bank Name :");
        jPanel2.add(cbq, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 120, -1));

        db.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        db.setForeground(new java.awt.Color(255, 255, 255));
        db.setText("Bank Name :");
        jPanel2.add(db, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 160, -1));

        cq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cq.setForeground(new java.awt.Color(255, 255, 255));
        cq.setText("Cheque No :");
        jPanel2.add(cq, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        jPanel2.add(utrn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 180, -1));

        utrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utrbActionPerformed(evt);
            }
        });
        jPanel2.add(utrb, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 390, -1));
        jPanel2.add(ddn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 180, -1));

        ddb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddbActionPerformed(evt);
            }
        });
        jPanel2.add(ddb, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 390, -1));

        jScrollPane2.setViewportView(jPanel2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 1060, 820));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/home.png"))); // NOI18N
        jLabel1.setText("  HOME");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 170, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 290, 80));

        course.setBackground(new java.awt.Color(0, 51, 51));
        course.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        course.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                courseMouseMoved(evt);
            }
        });
        course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                courseMouseExited(evt);
            }
        });
        course.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/edit2.png"))); // NOI18N
        jLabel3.setText(" COURSES");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        course.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 170, 60));

        jPanel1.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 290, 80));

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/smallfee.png"))); // NOI18N
        jLabel4.setText(" FEE STRUCTURE");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 240, 80));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 290, 80));

        jPanel7.setBackground(new java.awt.Color(0, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/view all record.png"))); // NOI18N
        jLabel5.setText("   REPORT");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 210, 80));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 290, 80));

        jPanel9.setBackground(new java.awt.Color(0, 51, 51));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/logout.png"))); // NOI18N
        jLabel38.setText("  LOG OUT");
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel38MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel38MouseExited(evt);
            }
        });
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 60));

        jPanel10.setBackground(new java.awt.Color(0, 51, 51));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/logout.png"))); // NOI18N
        jLabel39.setText("  LOG OUT");
        jPanel10.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 60));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 290, 80));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 290, 80));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        printfee.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        printfee.setForeground(new java.awt.Color(255, 255, 255));
        printfee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/printer-.png"))); // NOI18N
        printfee.setText("  PRINT FEES");
        printfee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printfeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printfeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printfeeMouseExited(evt);
            }
        });
        jPanel4.add(printfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 60));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 290, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 820));

        setSize(new java.awt.Dimension(1466, 823));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    String a,t,s,i,u,inter,si;
    Date d;
    boolean isValidations()
    {
    a=ad.getText();
    t=tu.getText();
    s=so.getText();
    i=in.getText();
    u=un.getText();
    inter=internal.getText();
    d=dt.getDate();
    si=(String) mode.getSelectedItem();
    if(d == null)
    {
     JOptionPane.showMessageDialog(this,"Please choose date of submission");   
     return false;
    }
    else if(a.equals(""))
    {
     JOptionPane.showMessageDialog(this,"Please Enter Admission fee");   
     return false;
    }
     else if(t.equals(""))
    {
     JOptionPane.showMessageDialog(this,"Please Enter tuition fee");   
     return false;
    }
     else if(s.equals(""))
    {
     JOptionPane.showMessageDialog(this,"Please Enter soft skill fee");   
     return false;
    }
     else if(i.equals(""))
    {
     JOptionPane.showMessageDialog(this,"Please Enter Industry training fee");   
     return false;
    }
     else if(u.equals(""))
    {
     JOptionPane.showMessageDialog(this,"Please Enter university fee");   
     return false;
    }
     else if(inter.equals(""))
    {
     JOptionPane.showMessageDialog(this,"Please Enter Internal Examination fee");   
     return false;
    }
     else if(si.equals("Cheque") && cheque.getText().equals(""))   //DDNEFT
    {
     JOptionPane.showMessageDialog(this,"Please Enter cheque no");   
     return false;
    }
    else if(si.equals("Cheque") && cbank.getText().equals(""))   //DDNEFT
    {
     JOptionPane.showMessageDialog(this,"Please Enter bank name");   
     return false;
    }
    else if(si.equals("DD") && ddn.getText().equals(""))   //DDNEFT
    {
     JOptionPane.showMessageDialog(this,"Please Enter DD no");   
     return false;
    }
    else if(si.equals("DD") && ddb.getText().equals(""))   //DDNEFT
    {
     JOptionPane.showMessageDialog(this,"Please Enter DD bank name");   
     return false;
    }
    else if(si.equals("NEFT") && utrn.getText().equals(""))   //DDNEFT
    {
     JOptionPane.showMessageDialog(this,"Please Enter UTR no");   
     return false;
    }
    else if(si.equals("NEFT") && utrb.getText().equals(""))   //DDNEFT
    {
     JOptionPane.showMessageDialog(this,"Please Enter Bank name");   
     return false;
    }
    return true;
    }
    
    int getAmt(String cor,int cyr)
    {    
    try
       {   
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/fdams","root","");
        String sql="select * from "+cor+cyr;
        PreparedStatement stmt;
        stmt = conn.prepareStatement(sql);
        ResultSet get=stmt.executeQuery();
        if(get.next())
        {
        return get.getInt("amount");
        }
       }
       catch(HeadlessException | ClassNotFoundException | SQLException e)
       {
       }
      return 0;
    }
    
    int gtPd(String cor,String phn)
    { 
    try
       {   
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/fdams","root","");
        String sql="select * from student where phone=?";
        PreparedStatement stmt;
        stmt = conn.prepareStatement(sql);
        stmt.setString(1,phn);
        ResultSet get=stmt.executeQuery();
        if(get.next())
        {
        return get.getInt("paid");
        }
       }
       catch(HeadlessException | ClassNotFoundException | SQLException e)
       {
       }
      return 0;
    }
    
    
    void upStudent(int tt,int blnc,String phn,String cor)
    {
    try
       {   
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/fdams","root","");
        String sql="update student set paid=paid+"+tt+",due=due-"+tt+" where phone=?";
        PreparedStatement stmt;
        stmt = conn.prepareStatement(sql);
        stmt.setString(1,phn);
        int gt=stmt.executeUpdate();
        if(gt>0)
        {
            
        }
       }
       catch(HeadlessException | ClassNotFoundException | SQLException e)
       {
           e.printStackTrace();
       }
    }
    
    void feeRec(String fr,String ls,int tl,int blc,String phn,String core,String rn)
    {
        
        long millis=System.currentTimeMillis();  
        java.sql.Date dat = new java.sql.Date(millis);
        int b,bl;
        if(blc<0)
        {
            b=blc;
            bl=0;
        }
        else
        {   
            b=0;
            bl=blc;
        }
       try
       {   
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/fdams","root","");
        
          
        String sql="insert into feedetails(course,first,last,phone,paid,due,excess,date,no) values(?,?,?,?,?,?,?,?,?)";
        PreparedStatement stmt;
        stmt = conn.prepareStatement(sql);
        stmt.setString(1,core);
        stmt.setString(2,fr);
        stmt.setString(3,ls);
        stmt.setString(4,phn);
        stmt.setInt(5,tl);
        stmt.setInt(6,bl);
        stmt.setInt(7,b);
        stmt.setDate(8,dat);
        stmt.setString(9,rn);

        stmt.executeUpdate();
       }
       catch(HeadlessException | ClassNotFoundException | SQLException e)
       {
           e.printStackTrace();
       }
    
    }
    
   
    
    private void printfeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printfeeMouseClicked
        // TODO add your handling code here:
       if(isValidations())
       {
        int tot=Integer.parseInt(a)+Integer.parseInt(t)+Integer.parseInt(s)+Integer.parseInt(i)+Integer.parseInt(u)+Integer.parseInt(inter);
        String cor=crse.getText();
        int ntot=gtPd(cor,phn.getText())+tot;
        int cryr=Integer.parseInt(yr.getText());
        int ttl=getAmt(cor,cryr);
        int blc=ttl-ntot;
        int nblc=0,ne=0;
        if(blc>0)
        {
        upStudent(tot,blc,phn.getText(),cor);
        feeRec(frst,lst,tot,blc,phn.getText(),cor,r.getText()+rno.getText());
        nblc=blc;
        ne=0;
        }
        else if(blc==0)
        {
        upStudent(tot,blc,phn.getText(),cor);
        feeRec(frst,lst,tot,blc,phn.getText(),cor,r.getText()+rno.getText());
        nblc=0;
        ne=0;
        }
        else if(blc<0)
        {
        upStudent(tot-Math.abs(blc),blc,phn.getText(),cor);
        feeRec(frst,lst,tot,blc,phn.getText(),cor,r.getText()+rno.getText());
        nblc=0;
        ne=Math.abs(blc);
        }
        Date dtee=dt.getDate();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
        String dte = dateFormat.format(dtee);  
        
        feer fri=new feer(rno.getText(),frst,lst,phon,co,cur,(String)mode.getSelectedItem(),cheque.getText(),cbank.getText(),ddn.getText(),ddb.getText(),utrn.getText(),utrb.getText(),dte,yr.getText(),a,t,s,i,u,inter,tot,nblc,ne,note.getText(),words.getText());
        fri.show();
        this.dispose(); 
       }
    }//GEN-LAST:event_printfeeMouseClicked

    private void cbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbankActionPerformed

    private void excessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excessActionPerformed

    private void pdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdActionPerformed

    private void blnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blnActionPerformed

    private void wordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wordsActionPerformed

    private void utrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utrbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utrbActionPerformed

    private void ddbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddbActionPerformed

    private void modeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeActionPerformed
        // TODO add your handling code here:
        if(mode.getSelectedItem().equals("Cheque"))  
        {
        cheque.show();
        cbank.show();        
        cq.show();        
        cbq.show();
        
        ded.hide();
        db.hide();
        ddn.hide();
        ddb.hide();
        
        utr.hide();
        crb.hide();
        utrn.hide();
        utrb.hide();
        
        }
        
        if(mode.getSelectedItem().equals("Cheque"))  
        {
        cheque.show();
        cbank.show();        
        cq.show();        
        cbq.show();
        
        ded.hide();
        db.hide();
        ddn.hide();
        ddb.hide();
        
        utr.hide();
        crb.hide();
        utrn.hide();
        utrb.hide();
        
        }
       
        else if(mode.getSelectedItem().equals("Cash"))  
        {
        ded.hide();
        db.hide();
        ddn.hide();
        ddb.hide();
        
        utr.hide();
        crb.hide();
        utrn.hide();
        utrb.hide();
        
        cheque.hide();
        cbank.hide();        
        cq.hide();        
        cbq.hide();
        }
        else if(mode.getSelectedItem().equals("NEFT")) 
        {
        utr.show();
        crb.show();
        utrn.show();
        utrb.show();
        
        ded.hide();
        db.hide();
        ddn.hide();
        ddb.hide();
        
        cheque.hide();
        cbank.hide();        
        cq.hide();        
        cbq.hide();
        }
    }//GEN-LAST:event_modeActionPerformed

    
String retword;        
public String[] UNITPLACE = { " ", "ONE ", "TWO ", "THREE ", "FOUR ", "FIVE ", "SIX ", "SEVEN ","EIGHT ", "NINE ", "TEN ", "ELEVEN ", "TWELVE ", "THIRTEEN ", "FOURTEEN ", "FIVETEEN ", "SIXTEEN ","SEVENTEEN ", "EIGHTEEN ", "NINETEEN " }; 
public String[] TENPLACE = { " ", "TWENTY ", "THIRTY ", "FOURTY ", "FIVETY ", "SIXTY ", "SEVENTY ","EIGHTY ", "NINETY " }; 
public String[] MOREPLACE = { " ", "HUNDRED ", "THOUSAND ", "LAKH ", "CRORE ", "ARAB ","KHARAB ","NIL ","PADM ","SANKH ","MAHA SANKH "}; 
//Call this function from main method and pass no ,digit=0,len=0 
  String numberSplit(long no, int digit, int len) { 
		if (no > 0) { 
			if (len == 2) 
				numberSplit(no / 10, (int) (no % 10), len + 1); 
			else 
				numberSplit(no / 100, (int) (no % 100), len + 2); 
		} 
		if (digit > 0) 
			retword= wordPrint(digit, len); 
                
                return retword+"ONLY";
	} 
        String wrd="";
	String wordPrint(int digit, int len) { 
		if (digit < 20) 
			wrd=wrd+UNITPLACE[digit]; 
		else { 
 
			wrd=wrd+TENPLACE[(digit / 10) - 1]; 
 
			if (digit % 10 != 0) 
				wrd=wrd+UNITPLACE[digit % 10]; 
		} 
		if (len > 2) 
			wrd=wrd+MOREPLACE[len / 2]; 
                
                return wrd;
	}
     
    
    private void frMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frMouseClicked
        // TODO add your handling code here:
        if(isValidations())
        {
        int tot=Integer.parseInt(a)+Integer.parseInt(t)+Integer.parseInt(s)+Integer.parseInt(i)+Integer.parseInt(u)+Integer.parseInt(inter);
        words.setText(numberSplit(tot,0,0));    
        pd.setText(Integer.toString(tot));
        int cyrs=Integer.parseInt(yr.getText());
        String cors=crse.getText();
        int ntot=gtPd(cors,phn.getText())+tot;
        int ttl=getAmt(cors,cyrs);
        int blnc=ttl-ntot;
        if(blnc<0)
        {
            excess.setText(Integer.toString(Math.abs(blnc)));
            bln.setText("0");
        }
        else if(blnc>0)
        {
            bln.setText(Integer.toString(blnc));
            excess.setText("0");
        }    
        } 
    }//GEN-LAST:event_frMouseClicked

    private void internalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_internalFocusLost
        // TODO add your handling code here:
        if(isValidations())
        {
        int tot=Integer.parseInt(a)+Integer.parseInt(t)+Integer.parseInt(s)+Integer.parseInt(i)+Integer.parseInt(u)+Integer.parseInt(inter);
        words.setText(numberSplit(tot,0,0));    
        pd.setText(Integer.toString(tot));
        int cyrs=Integer.parseInt(yr.getText());
        String cors=crse.getText();
        int ntot=gtPd(cors,phn.getText())+tot;
        int ttl=getAmt(cors,cyrs);
        int blnc=ttl-ntot;
        if(blnc<0)
        {
            excess.setText(Integer.toString(Math.abs(blnc)));
            bln.setText("0");
        }
        else if(blnc>0)
        {
            bln.setText(Integer.toString(blnc));
            excess.setText("0");
        }
        } 
    }//GEN-LAST:event_internalFocusLost

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        studentfeerecord cv=new studentfeerecord();
        cv.show();
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        Color col=new Color(105,105,105);
        jPanel3.setBackground(col);
        jPanel3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        Color col=new Color(0,51,51);
        jPanel3.setBackground(col);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        core c=new core();
        c.show();
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        Color col=new Color(105,105,105);
        course.setBackground(col);
        course.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        Color col=new Color(0,51,51);
        course.setBackground(col);
    }//GEN-LAST:event_jLabel3MouseExited

    private void courseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseMouseMoved
        // TODO add your handling code here:
        course.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        Color col=new Color(105,105,105);
        course.setBackground(col);
    }//GEN-LAST:event_courseMouseMoved

    private void courseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseMouseClicked
        // TODO add your handling code here:
        core cor=new core();
        cor.show();
        this.dispose();
    }//GEN-LAST:event_courseMouseClicked

    private void courseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseMouseExited
        // TODO add your handling code here:
        Color col=new Color(0,51,51);
        course.setBackground(col);
    }//GEN-LAST:event_courseMouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        feesearch fs=new feesearch();
        fs.show();
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        Color col=new Color(105,105,105);
        jPanel6.setBackground(col);
        jPanel6.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        Color col=new Color(0,51,51);
        jPanel6.setBackground(col);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        feerec stu=new feerec();
        stu.show();
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        Color col=new Color(105,105,105);
        jPanel7.setBackground(col);
        jPanel7.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        Color col=new Color(0,51,51);
        jPanel7.setBackground(col);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        // TODO add your handling code here:
        login lg=new login();
        lg.show();
        this.dispose();
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jLabel38MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseEntered
        // TODO add your handling code here:
        Color col=new Color(105,105,105);
        jPanel9.setBackground(col);
        jPanel9.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel38MouseEntered

    private void jLabel38MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseExited
        // TODO add your handling code here:
        Color col=new Color(0,51,51);
        jPanel9.setBackground(col);
    }//GEN-LAST:event_jLabel38MouseExited

    private void printfeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printfeeMouseEntered
        // TODO add your handling code here:
         Color col=new Color(105,105,105);
        jPanel4.setBackground(col);
        jPanel4.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_printfeeMouseEntered

    private void printfeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printfeeMouseExited
        // TODO add your handling code here:
         Color col=new Color(0,51,51);
        jPanel4.setBackground(col);
    }//GEN-LAST:event_printfeeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feereceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feereceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feereceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feereceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feereceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private javax.swing.JTextField bln;
    private javax.swing.JTextField cbank;
    private javax.swing.JLabel cbq;
    private javax.swing.JTextField cheque;
    private javax.swing.JPanel course;
    private javax.swing.JLabel cq;
    private javax.swing.JLabel cr;
    private javax.swing.JLabel crb;
    private javax.swing.JLabel crse;
    private javax.swing.JLabel cyr;
    private javax.swing.JLabel db;
    private javax.swing.JTextField ddb;
    private javax.swing.JTextField ddn;
    private javax.swing.JLabel ded;
    private com.toedter.calendar.JDateChooser dt;
    private javax.swing.JLabel due;
    private javax.swing.JLabel duratn;
    private javax.swing.JTextField excess;
    private javax.swing.JLabel fname;
    private javax.swing.JPanel fr;
    private javax.swing.JTextField in;
    private javax.swing.JTextField internal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lname;
    private javax.swing.JComboBox<String> mode;
    private javax.swing.JTextPane note;
    private javax.swing.JLabel paid;
    private javax.swing.JTextField pd;
    private javax.swing.JLabel phn;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel printfee;
    private javax.swing.JLabel r;
    private javax.swing.JLabel received;
    private javax.swing.JLabel rno;
    private javax.swing.JTextField so;
    private javax.swing.JTextField tu;
    private javax.swing.JTextField un;
    private javax.swing.JLabel utr;
    private javax.swing.JTextField utrb;
    private javax.swing.JTextField utrn;
    private javax.swing.JTextField words;
    private javax.swing.JLabel yr;
    // End of variables declaration//GEN-END:variables
}
