/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fdams;

//import com.mysql.cj.Session;
//import com.mysql.cj.protocol.Message;
//import com.sun.jdi.connect.Transport;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.Random;
import javax.mail.MessagingException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.Message;


/**
 *
 * @author LENOVO
 */
public class forget extends javax.swing.JFrame {

    /**
     * Creates new form forget
     */
    public forget() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mailid = new javax.swing.JTextField();
        sendcode = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        verify = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        sent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/pass.png"))); // NOI18N
        jLabel1.setText("  Forgot Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 240, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 80));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Your email :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 86, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter code :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 174, -1, -1));
        jPanel2.add(mailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 240, 30));

        sendcode.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        sendcode.setForeground(new java.awt.Color(102, 255, 255));
        sendcode.setText("Send code?");
        sendcode.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                sendcodeMouseMoved(evt);
            }
        });
        sendcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendcodeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sendcodeMousePressed(evt);
            }
        });
        jPanel2.add(sendcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));
        jPanel2.add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 240, 30));

        verify.setBackground(new java.awt.Color(255, 51, 51));
        verify.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        verify.setForeground(new java.awt.Color(255, 255, 255));
        verify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/verify.png"))); // NOI18N
        verify.setText("Verify");
        verify.setBorder(null);
        verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyActionPerformed(evt);
            }
        });
        jPanel2.add(verify, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 100, 40));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/back1.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 100, 40));

        sent.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        sent.setForeground(new java.awt.Color(204, 255, 255));
        jPanel2.add(sent, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 240, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 730, 410));

        setSize(new java.awt.Dimension(741, 494));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        login log=new login();
        log.show();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    //validation
    
    
    
     boolean isValid(String email) {
     String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(email);
           return m.matches();
   }
     
     boolean isValidCode(String code) {
     String ePattern = "^[1-9]+[0-9]*$";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(code);
           return m.matches();
   }
     
    
    String mail,ccode;

   
    
    boolean mailExist()
    {
       boolean res = false;
       mail=mailid.getText();
       try
       {   
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/fdams","root","");
        String sql="select * from user where mailid=?";
        PreparedStatement stmt;
        stmt = conn.prepareStatement(sql);
        stmt.setString(1,mail);
           ResultSet get=stmt.executeQuery();
        if(get.next())
        {
        res=true;
        }
        else 
        {
            res=false;
        }
       }
       catch(HeadlessException | ClassNotFoundException | SQLException e)
       {
       }
       return res;
    } 
    

    boolean isValidate()
    {
    mail=mailid.getText();
    ccode=code.getText();
    if(ccode.equals(""))
    {
    JOptionPane.showMessageDialog(this,"Please Enter a code you received in your registered email");
    return false;
    }    
    else if(!isValidCode(ccode))
    {
     JOptionPane.showMessageDialog(this,"Code is in digits");
     return false;
    }
    return true;
    }
    
    
    
    
    

//sendcode
    int randomCode;
    void sendCode() 
    {
      Random rand=new Random();
      randomCode = rand.nextInt(999999);
      
     
      String host = "smtp.gmail.com";
      
      String too = mailid.getText();
      // Sender's email ID needs to be mentioned
      String from = "amanagarwal7760@gmail.com";
      String pass="Aman954@";
      String subject="Reset your code";
      String msg="Your reset code is "+randomCode;
      boolean sessionDebug=false;
      // Get system properties
      Properties properties = System.getProperties();
      properties.setProperty("mail.smtp.starttls.enable", "true");
      properties.setProperty("mail.smtp.ssl.protocols", "TLSv1.2");
      //Properties properties = new Properties();
      properties.put("mail.smtp.starttls.enable","true");
      properties.put("mail.smtp.host",host);
      properties.put("mail.smtp.port","587"); //587
      properties.put("mail.transport.protocol", "smtp");
      properties.put("mail.smtp.auth","true");
      properties.put("mail.smtp.starttls.required","true");
      

      
      java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
      
      // Get the default Session object.
      Session session;
      session = Session.getDefaultInstance(properties,null);
      
      session.setDebug(sessionDebug);
      

      
try 
{
         MimeMessage message = new MimeMessage(session);

         // Set From: header field of the header.
         message.setFrom(new InternetAddress(from));

         // Set To: header field of the header.
         message.setRecipient(Message.RecipientType.TO, new InternetAddress(too));

         // Set Subject: header field
         message.setSubject(subject);

         // Now set the actual message
         message.setText(msg);

         // Send message
         
         
         Transport tp=session.getTransport("smtp");
         tp.connect(host,from,pass);
         tp.sendMessage(message,message.getAllRecipients());
         tp.close();
         sendcode.hide();
         sent.setText("code has been sent");
         //JOptionPane.showMessageDialog(this,"code has been sent");
}
catch(MessagingException e)
{
    e.printStackTrace();
}
        
}
    

void verifyCode()
{
ccode=code.getText();
String ran=Integer.toString(randomCode);
if(ccode.equals(ran))
{
reset rs=new reset(mailid.getText());
rs.show();
this.dispose();
}
else 
{
JOptionPane.showMessageDialog(this,"Incorrect code");
}
}
    
    
    private void verifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyActionPerformed
        // TODO add your handling code here:
        if(isValidate())
        {
        verifyCode();
        }
    }//GEN-LAST:event_verifyActionPerformed

    private void sendcodeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendcodeMousePressed
        // TODO add your handling code here:
        mail=mailid.getText();
        if(!isValid(mail))
        {
        JOptionPane.showMessageDialog(this,"Please enter a valid email");
        }
        else if(!mailExist())
        {
         JOptionPane.showMessageDialog(this,"This mail id isnot registred with us");
        }
        else 
        {
         sendCode();
        }    
    }//GEN-LAST:event_sendcodeMousePressed

    private void sendcodeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendcodeMouseMoved
        // TODO add your handling code here:
        sendcode.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        Color col=new Color(0,0,0,254);
        sendcode.setForeground(col);
    }//GEN-LAST:event_sendcodeMouseMoved

    private void sendcodeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendcodeMouseExited
        // TODO add your handling code here:
        Color col=new Color(153,255,153);
        sendcode.setForeground(col);
    }//GEN-LAST:event_sendcodeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forget().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField code;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField mailid;
    private javax.swing.JLabel sendcode;
    private javax.swing.JLabel sent;
    private javax.swing.JButton verify;
    // End of variables declaration//GEN-END:variables
}
