/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fdams;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;

/**
 *
 * @author LENOVO
 */
public class printfee extends javax.swing.JFrame {

    /**
     * Creates new form printfee
     */
    public printfee() {
        initComponents();
    }
    
    public printfee(String adm,String tui,String sof,String ind,String uni,String intern,String tot,String word,String notes,String crs,String y){
        initComponents();
        cr.setText(crs);
        yr.setText(y);
        ad.setText(adm);
        tu.setText(tui);
        so.setText(sof);
        in.setText(ind);
        un.setText(uni);
        inter.setText(intern);
        total.setText(tot);
        inwords.setText(word);
        note.setText(notes);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        prin = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        bck = new javax.swing.JLabel();
        feeprin = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        cr = new javax.swing.JLabel();
        tu = new javax.swing.JLabel();
        so = new javax.swing.JLabel();
        in = new javax.swing.JLabel();
        un = new javax.swing.JLabel();
        ad = new javax.swing.JLabel();
        yr = new javax.swing.JLabel();
        inter = new javax.swing.JLabel();
        inwords = new javax.swing.JLabel();
        note = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        prin.setForeground(new java.awt.Color(255, 255, 255));
        prin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/printer-.png"))); // NOI18N
        prin.setText("  PRINT");
        prin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prinMouseClicked(evt);
            }
        });
        jPanel4.add(prin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 170, 80));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 1290, 210, 80));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bck.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bck.setForeground(new java.awt.Color(255, 255, 255));
        bck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/back-button.png"))); // NOI18N
        bck.setText("  BACK");
        bck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bckMouseClicked(evt);
            }
        });
        jPanel5.add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 170, 80));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1290, 200, 80));

        feeprin.setBackground(new java.awt.Color(255, 255, 255));
        feeprin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(102, 0, 102));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 32)); // NOI18N
        jLabel8.setText("Shivalik");
        feeprin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 52)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 102));
        jLabel9.setText("College Of Engineering");
        feeprin.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setText("P.O, Shimla Bypass Road Shiniwala, Sherpur, Uttarakhand 248197, Phone: 099971 55111");
        feeprin.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, 20));

        jPanel9.setBackground(new java.awt.Color(102, 0, 102));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        feeprin.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 1210, 7));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        jLabel14.setText("Course :");
        feeprin.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel11.setText("Amount");
        feeprin.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 290, 110, 50));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel13.setText("S.NO");
        feeprin.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 80, 50));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel15.setText("Tuition fees ");
        feeprin.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, -1, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel16.setText("Soft skill training");
        feeprin.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, 240, 70));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel17.setText("Industrial training");
        feeprin.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 640, 250, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel18.setText("University fees");
        feeprin.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 730, 240, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel19.setText("Internal examination fees ");
        feeprin.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 810, -1, 50));

        total.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        total.setForeground(new java.awt.Color(102, 0, 102));
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("6670");
        feeprin.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 890, 110, 40));

        cr.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        cr.setForeground(new java.awt.Color(102, 0, 102));
        feeprin.add(cr, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 140, 30));

        tu.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        tu.setForeground(new java.awt.Color(102, 0, 102));
        tu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tu.setText("5699");
        feeprin.add(tu, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 460, 140, 40));

        so.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        so.setForeground(new java.awt.Color(102, 0, 102));
        so.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        so.setText("6789");
        feeprin.add(so, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, 160, 30));

        in.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        in.setForeground(new java.awt.Color(102, 0, 102));
        in.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        in.setText("7890");
        feeprin.add(in, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 630, 120, 40));

        un.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        un.setForeground(new java.awt.Color(102, 0, 102));
        un.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        un.setText("9890");
        feeprin.add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 730, 140, 30));

        ad.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        ad.setForeground(new java.awt.Color(102, 0, 102));
        ad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ad.setText("4500");
        feeprin.add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 390, 140, 30));

        yr.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        yr.setForeground(new java.awt.Color(102, 0, 102));
        yr.setText("1");
        feeprin.add(yr, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 190, 80, 40));

        inter.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        inter.setForeground(new java.awt.Color(102, 0, 102));
        inter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inter.setText("9870");
        feeprin.add(inter, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 810, 180, 40));

        inwords.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        inwords.setForeground(new java.awt.Color(102, 0, 102));
        inwords.setText("sasa");
        feeprin.add(inwords, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 980, 940, 40));

        note.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        note.setForeground(new java.awt.Color(102, 0, 102));
        note.setText("ssd");
        feeprin.add(note, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 1020, 1030, 50));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        jLabel21.setText("Amount in words : ");
        feeprin.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 980, -1, 40));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setText("Note :");
        feeprin.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1030, -1, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel20.setText("6");
        feeprin.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 810, -1, 50));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        jLabel23.setText("Year :");
        feeprin.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 190, 80, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel24.setText("Head");
        feeprin.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, 50));

        jSeparator1.setForeground(new java.awt.Color(0, 153, 153));
        feeprin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 860, 20));
        feeprin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 870, 200, 10));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel25.setText("Admission fees ");
        feeprin.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, -1, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel26.setText("1");
        feeprin.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, 50));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel27.setText("2");
        feeprin.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, 50));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel29.setText("3");
        feeprin.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, -1, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel30.setText("4");
        feeprin.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 640, -1, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel31.setText("5");
        feeprin.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 730, 30, 30));
        feeprin.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 860, 20));

        jPanel2.add(feeprin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 1200));

        jScrollPane2.setViewportView(jPanel2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1460, 820));

        setSize(new java.awt.Dimension(1468, 823));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
  
    
    
    private void prinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prinMouseClicked
        // TODO add your handling code here:
        
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable((Graphics pg, PageFormat pf, int pageNum) -> {
                pf.setOrientation(PageFormat.LANDSCAPE);
                if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                feeprin.print(g2);
                
                
                return Printable.PAGE_EXISTS;
        });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }

        
    }//GEN-LAST:event_prinMouseClicked

    private void bckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bckMouseClicked
        // TODO add your handling code here:
        
        courses crp=new courses();
        crp.show();
        this.dispose();
    }//GEN-LAST:event_bckMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printfee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printfee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printfee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printfee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printfee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ad;
    private javax.swing.JLabel bck;
    private javax.swing.JLabel cr;
    private javax.swing.JPanel feeprin;
    private javax.swing.JLabel in;
    private javax.swing.JLabel inter;
    private javax.swing.JLabel inwords;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel note;
    private javax.swing.JLabel prin;
    private javax.swing.JLabel so;
    private javax.swing.JLabel total;
    private javax.swing.JLabel tu;
    private javax.swing.JLabel un;
    private javax.swing.JLabel yr;
    // End of variables declaration//GEN-END:variables
}
