/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fdams;

import java.awt.HeadlessException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class reset extends javax.swing.JFrame {

    /**
     * Creates new form reset
     */
    public reset() {
        initComponents();
    }
    
    public String ml;
    
    public reset(String mail) {
        this.ml=mail;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        npass = new javax.swing.JPasswordField();
        cnpass = new javax.swing.JPasswordField();
        res = new javax.swing.JButton();
        alert = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/reset.png"))); // NOI18N
        jLabel1.setText(" Reset Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 80));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New password :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm password :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, 30));

        npass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                npassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                npassKeyReleased(evt);
            }
        });
        jPanel2.add(npass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 200, 30));
        jPanel2.add(cnpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 200, 30));

        res.setBackground(new java.awt.Color(51, 0, 51));
        res.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        res.setForeground(new java.awt.Color(255, 255, 255));
        res.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/login.png"))); // NOI18N
        res.setText(" Reset");
        res.setBorder(null);
        res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resActionPerformed(evt);
            }
        });
        jPanel2.add(res, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 272, 130, 40));

        alert.setForeground(new java.awt.Color(0, 0, 102));
        jPanel2.add(alert, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 200, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 730, 420));

        setSize(new java.awt.Dimension(741, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    String pass,cpass;
     void passwordValidate()
    {
     pass=npass.getText();
     if(pass.length()<8)
     {
      alert.setText("Password should be 8 character long");
     }
     else 
     {
     alert.setText("");
     }
    
    }  
    
     boolean isValidate()
     {
      pass=npass.getText();
      cpass=cnpass.getText();
     if(pass.equals(""))
    {
        JOptionPane.showMessageDialog(this,"Please enter your password");
        return false;
    }
     else if(cpass.equals(""))
    {
        JOptionPane.showMessageDialog(this,"Please confirm your password");
        return false;
    }
    else if(!pass.equals(cpass))
    {
        JOptionPane.showMessageDialog(this,"Password not matched");
        return false;
    }
    else if(pass.length()<8)
    {
        JOptionPane.showMessageDialog(this,"Password must be 8 character long");
        return false;
    }
     
     return true;
     }
     
     
     
     String encDyc(String password)
    {
    String encryptedpassword = null;  
        try   
        {  
            /* MessageDigest instance for MD5. */  
            MessageDigest m = MessageDigest.getInstance("MD5");  
              
            /* Add plain-text password bytes to digest using MD5 update() method. */  
            m.update(password.getBytes());  
              
            /* Convert the hash value into bytes */   
            byte[] bytes = m.digest();  
              
            /* The bytes array has bytes in decimal form. Converting it into hexadecimal format. */  
            StringBuilder s = new StringBuilder();  
            for(int i=0; i< bytes.length ;i++)  
            {  
                s.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));  
            }  
              
            /* Complete hashed password in hexadecimal format */  
            encryptedpassword = s.toString();  
        }   
        catch (NoSuchAlgorithmException e)   
        {  
        }  
    
        return encryptedpassword;
    
    }
     
     
     
     
     
     void updatePass()
     {
     pass=npass.getText();
     String npas=encDyc(pass);
    
     try
       {   
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/fdams","root","");
        String sql="UPDATE user SET password=? where mailid=?";
        PreparedStatement stmt;
        stmt = conn.prepareStatement(sql);
        stmt.setString(1,npas);
        stmt.setString(2,ml);
        int get=stmt.executeUpdate();
        if(get>0)
        {
        JOptionPane.showMessageDialog(this,"Your password is updated");
        login log=new login();
        log.show();
        this.dispose();
        }
        else 
         JOptionPane.showMessageDialog(this,"Something wrong!");

       }
       catch(HeadlessException | ClassNotFoundException | SQLException e)
       {
           e.printStackTrace();
       }
       System.out.println(ml);
     
     }
     
     
     
     
    
    private void resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resActionPerformed
        // TODO add your handling code here:
        if(isValidate())
        {
          updatePass();
        }
    }//GEN-LAST:event_resActionPerformed

    private void npassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_npassKeyPressed
        // TODO add your handling code here:
        passwordValidate();
    }//GEN-LAST:event_npassKeyPressed

    private void npassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_npassKeyReleased
        // TODO add your handling code here:
                passwordValidate();
    }//GEN-LAST:event_npassKeyReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.JPasswordField cnpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField npass;
    private javax.swing.JButton res;
    // End of variables declaration//GEN-END:variables
}
