/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fdams;
//import com.sun.jdi.connect.spi.Connection;
import java.awt.HeadlessException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.*;

/**
 *
 * @author LENOVO
 */
public class signup extends javax.swing.JFrame {

    private Object JoptionPane;

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        mailid = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        cpassword = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        dob = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        alert = new javax.swing.JLabel();
        err = new javax.swing.JLabel();
        alerts = new javax.swing.JLabel();
        errs = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel9.setForeground(new java.awt.Color(153, 255, 255));
        jLabel9.setText("Pass");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 14, -1, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 36, -1, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/signup.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 70));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("First name :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Last name :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 120, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Mail id :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Password :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 120, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Confirm password :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 190, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("DOB :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 70, -1));

        txt_fname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fnameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 209, 31));

        lname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 209, 31));

        mailid.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(mailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 209, 31));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 209, 31));
        jPanel2.add(cpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 209, 31));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Role :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 70, -1));

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accounts", "Registrar" }));
        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });
        jPanel2.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 209, 31));
        jPanel2.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 207, 31));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Phone number :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 170, 30));

        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneKeyReleased(evt);
            }
        });
        jPanel2.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 209, 31));

        submit.setBackground(new java.awt.Color(255, 0, 0));
        submit.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/add2.png"))); // NOI18N
        submit.setText("Submit");
        submit.setBorder(null);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel2.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, 110, 40));

        back.setBackground(new java.awt.Color(0, 51, 51));
        back.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/back1.png"))); // NOI18N
        back.setText("Back");
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 120, 40));

        alert.setForeground(new java.awt.Color(0, 255, 255));
        jPanel2.add(alert, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 269, 209, -1));

        err.setForeground(new java.awt.Color(0, 255, 255));
        jPanel2.add(err, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 515, 209, -1));

        alerts.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(alerts, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 210, -1));

        errs.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(errs, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 210, -1));

        jLabel13.setText("jLabel13");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, -1, -1));

        jLabel14.setText("jLabel14");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, -1, -1));

        jLabel15.setText("jLabel15");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, -1, -1));

        jLabel16.setText("jLabel16");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, -1, 10));

        jLabel17.setText("jLabel17");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 620, 700));

        setSize(new java.awt.Dimension(634, 791));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    

    
    
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        login log=new login();
        log.show();
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    
    boolean isValid(String email) {
     String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(email);
           return m.matches();
   }
    
boolean isValidMobileNo(String phoneno)  
{  
Pattern ptrn = Pattern.compile("(0/91)?[7-9][0-9]{9}");  
Matcher match = ptrn.matcher(phoneno);  
return (match.find() && match.group().equals(phoneno));  
} 
    
    // validate first name
   boolean firstName( String firstName ) {
      return firstName.matches( "[A-Z][a-z]*" );
   }
   // validate last name
   boolean lastName( String lastName ) {
      return lastName.matches( "[A-Z][a-z]*" );
   }
    
    String firstname,lastname,email,phoneno,pass,cpass,urole;
    Date dofb;
       
 
    
    boolean isValidate()
    {
    firstname =txt_fname.getText();
    lastname=lname.getText();
    email=mailid.getText();
    phoneno=phone.getText();
    pass=password.getText();
    cpass=cpassword.getText();
    urole=role.getSelectedItem().toString();
    dofb=dob.getDate();
    
    if(firstname.equals(""))
    {
        JOptionPane.showMessageDialog(this,"Please enter your first name ");
        return false;
    }
    else if(lastname.equals(""))
    {
        JOptionPane.showMessageDialog(this,"Please enter your last name ");
        return false;
    }
    else if(email.equals(""))
    {
        JOptionPane.showMessageDialog(this,"Please enter your mail id ");
        return false;
    }
    else if(phoneno.equals(""))
    {
        JOptionPane.showMessageDialog(this,"Please enter your phone number");
        return false;
    }
    else if(pass.equals(""))
    {
        JOptionPane.showMessageDialog(this,"Please enter your password");
        return false;
    }
     else if(cpass.equals(""))
    {
        JOptionPane.showMessageDialog(this,"Please confirm your password");
        return false;
    }
    else if(dofb == null)
    {
        JOptionPane.showMessageDialog(this,"Please enter your date of birth");
        return false;
    }
    else if(!pass.equals(cpass))
    {
        JOptionPane.showMessageDialog(this,"Password not matched");
        return false;
    }
    else if(pass.length()<8)
    {
        JOptionPane.showMessageDialog(this,"Password must be 8 character long");
        return false;
    }
    else if(phoneno.length()!=10)
    {
        JOptionPane.showMessageDialog(this,"Phone number must be of 10 digits");
        return false;
    }
    else if(!isValid(email))
    {
        JOptionPane.showMessageDialog(this,"Please enter valid email!");
        return false;
    }
    else if(!isValidMobileNo(phoneno))
    {
        JOptionPane.showMessageDialog(this,"Please enter valid mobile no");
        return false;
    }
    else if(!firstName(firstname))
    {
        JOptionPane.showMessageDialog(this,"Only letter is allowed in first name");
        return false;
    }
    else if(!lastName(lastname))
    {
        JOptionPane.showMessageDialog(this,"Only letter is allowed in last name");
        return false;
    }
    return true;
    }
    
    void passwordValidate()
    {
     pass=password.getText();
     if(pass.length()<8)
     {
      alerts.setText("Password should be 8 character long");
     }
     else 
     {
     alerts.setText("");
     }
    
    }        
    
    void phonenoValidate()
    {
    phoneno=phone.getText();
     if(phoneno.length()!=10)
     {
      errs.setText("Phone number must be of 10 digits");
     }
     else 
     {
      errs.setText("");
     }
    
    }
    
   
    //chechmailexist
    
    boolean mailExist()
    {
       boolean res = false;
       email=mailid.getText();
       try
       {   
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/fdams","root","");
        String sql="select * from user where mailid=?";
        PreparedStatement stmt;
        stmt = conn.prepareStatement(sql);
        stmt.setString(1,email);
           ResultSet get=stmt.executeQuery();
        if(get.next())
        {
        JOptionPane.showMessageDialog(this,"This mail id already registered with us");
        res=true;
        }
        else 
            res=false;
       }
       catch(HeadlessException | ClassNotFoundException | SQLException e)
       {
       }
       return res;
    }
    
    
    //encrypt-decrypt-pass
    
    String encDyc(String password)
    {
    String encryptedpassword = null;  
        try   
        {  
            /* MessageDigest instance for MD5. */  
            MessageDigest m = MessageDigest.getInstance("MD5");  
              
            /* Add plain-text password bytes to digest using MD5 update() method. */  
            m.update(password.getBytes());  
              
            /* Convert the hash value into bytes */   
            byte[] bytes = m.digest();  
              
            /* The bytes array has bytes in decimal form. Converting it into hexadecimal format. */  
            StringBuilder s = new StringBuilder();  
            for(int i=0; i< bytes.length ;i++)  
            {  
                s.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));  
            }  
              
            /* Complete hashed password in hexadecimal format */  
            encryptedpassword = s.toString();  
        }   
        catch (NoSuchAlgorithmException e)   
        {  
        }  
    
        return encryptedpassword;
    
    }
    
                                    
    //usersubmit
    
    void userSubmit()
    {
     String npass=encDyc(pass);
     SimpleDateFormat ndob=new SimpleDateFormat("yyyy-MM-dd");
     String fdob=ndob.format(dofb);
     
     try
       {   
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/fdams","root","");
        String sql="insert into user(fname,lname,mailid,password,dob,role,phone) values(?,?,?,?,?,?,?)";
        PreparedStatement stmt;
        stmt = conn.prepareStatement(sql);
        stmt.setString(1,firstname);
        stmt.setString(2,lastname);
        stmt.setString(3,email);
        stmt.setString(4,npass);
        stmt.setString(5,fdob);
        stmt.setString(6,urole);
        stmt.setString(7,phoneno);

        int get=stmt.executeUpdate();
        if(get>0)
        {
        JOptionPane.showMessageDialog(this,"User Successfully registered");
        }
        else 
        {
        JOptionPane.showMessageDialog(this,"Some technical glitch..try again!");
        }
       }
       catch(HeadlessException | ClassNotFoundException | SQLException e)
       {
           e.printStackTrace();
       }
       }
    
    
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if(isValidate())
        {
            if (!mailExist()) {   
                userSubmit();
                login log=new login();
                log.show();
                this.dispose();
            }
        } 
    }//GEN-LAST:event_submitActionPerformed

    private void txt_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fnameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        passwordValidate();
    }//GEN-LAST:event_passwordKeyPressed

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
        // TODO add your handling code here:
                passwordValidate();

    }//GEN-LAST:event_passwordKeyReleased

    private void phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyPressed
        // TODO add your handling code here:
        phonenoValidate();
    }//GEN-LAST:event_phoneKeyPressed

    private void phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyReleased
        // TODO add your handling code here:
                phonenoValidate();

    }//GEN-LAST:event_phoneKeyReleased

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.JLabel alerts;
    private javax.swing.JButton back;
    private javax.swing.JPasswordField cpassword;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JLabel err;
    private javax.swing.JLabel errs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mailid;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JButton submit;
    private javax.swing.JTextField txt_fname;
    // End of variables declaration//GEN-END:variables
}
