/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fdams;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class updaterecord1 extends javax.swing.JFrame {

    /**
     * Creates new form updaterecord
     */
    public updaterecord1() {
        initComponents();
    }
    String cr,y,retword;
    int yr;
   
    
public String[] UNITPLACE = { " ", "ONE ", "TWO ", "THREE ", "FOUR ", "FIVE ", "SIX ", "SEVEN ","EIGHT ", "NINE ", "TEN ", "ELEVEN ", "TWELVE ", "THIRTEEN ", "FOURTEEN ", "FIVETEEN ", "SIXTEEN ","SEVENTEEN ", "EIGHTEEN ", "NINETEEN " }; 
 
public String[] TENPLACE = { " ", "TWENTY ", "THIRTY ", "FOURTY ", "FIVETY ", "SIXTY ", "SEVENTY ","EIGHTY ", "NINETY " }; 
 
public String[] MOREPLACE = { " ", "HUNDRED ", "THOUSAND ", "LAKH ", "CRORE ", "ARAB ","KHARAB ","NIL ","PADM ","SANKH ","MAHA SANKH "}; 
//Call this function from main method and pass no ,digit=0,len=0 
  String numberSplit(long no, int digit, int len) { 
		if (no > 0) { 
			if (len == 2) 
				numberSplit(no / 10, (int) (no % 10), len + 1); 
			else 
				numberSplit(no / 100, (int) (no % 100), len + 2); 
		} 
		if (digit > 0) 
			retword= wordPrint(digit, len); 
                
                return retword+"ONLY";
	} 
        String wrd="";
	String wordPrint(int digit, int len) { 
		if (digit < 20) 
			wrd=wrd+UNITPLACE[digit]; 
		else { 
 
			wrd=wrd+TENPLACE[(digit / 10) - 1]; 
 
			if (digit % 10 != 0) 
				wrd=wrd+UNITPLACE[digit % 10]; 
		} 
		if (len > 2) 
			wrd=wrd+MOREPLACE[len / 2]; 
                
                return wrd;
	}
    
    
    
    
    int drtn;
    
    public updaterecord1(String course,String addmission,String tui,String sof,String indus,String univ,String inter,String year,String amount,int duration) {
        initComponents();
        setcourse1.setText(course);
        setduration.setText(year);
        admission.setText(addmission);
        tuition.setText(tui);
        soft.setText(sof);
        industrial.setText(indus);
        university.setText(univ);
        internal.setText(inter);
        words.setText(numberSplit(Integer.parseInt(amount),0,0));
        total.setText(amount);
        this.cr=course;
        yr=Integer.parseInt(year);
        y=year;
        this.drtn=duration;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        setduration = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        setcourse1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        words = new javax.swing.JTextField();
        admission = new javax.swing.JTextField();
        tuition = new javax.swing.JTextField();
        soft = new javax.swing.JTextField();
        industrial = new javax.swing.JTextField();
        university = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        internal = new javax.swing.JTextField();
        up = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        notes = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        course = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        print = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("Year :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, -1, -1));

        setduration.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setduration.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(setduration, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, 60, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("P.O, Shimla Bypass Road Shiniwala, Sherpur, Uttarakhand 248197, Phone: 099971 55111");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 31)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("College Of Engineering");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Shivalik");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 255, 255));
        jLabel11.setText("TOTAL :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 630, -1, 40));

        setcourse1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setcourse1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(setcourse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 110, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 780, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 255, 255));
        jLabel13.setText("Admission fees :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 255, 255));
        jLabel14.setText("Amount in words : ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 680, 130, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 255, 255));
        jLabel15.setText("Tuition fees :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 255, 255));
        jLabel16.setText("Soft skill training :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 372, -1, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 255, 255));
        jLabel17.setText("Industrial training :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 255, 255));
        jLabel18.setText("University fees :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 498, -1, -1));

        words.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordsActionPerformed(evt);
            }
        });
        jPanel2.add(words, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 680, 560, 30));

        admission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admissionActionPerformed(evt);
            }
        });
        jPanel2.add(admission, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 170, 30));

        tuition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuitionActionPerformed(evt);
            }
        });
        jPanel2.add(tuition, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 170, 30));

        soft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                softActionPerformed(evt);
            }
        });
        jPanel2.add(soft, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 170, 30));

        industrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                industrialActionPerformed(evt);
            }
        });
        jPanel2.add(industrial, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 170, 30));

        university.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                universityActionPerformed(evt);
            }
        });
        jPanel2.add(university, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, 170, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 610, 200, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 255, 255));
        jLabel19.setText("Internal examination fees :");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, -1, 30));

        internal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                internalFocusLost(evt);
            }
        });
        internal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internalActionPerformed(evt);
            }
        });
        jPanel2.add(internal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 550, 170, 30));

        up.setBackground(new java.awt.Color(51, 0, 51));
        up.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        up.setForeground(new java.awt.Color(255, 255, 255));
        up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/update.png"))); // NOI18N
        up.setText(" Update");
        up.setBorder(null);
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        jPanel2.add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 120, 40));

        notes.setColumns(20);
        notes.setRows(5);
        jScrollPane1.setViewportView(notes);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 720, 640, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 255, 255));
        jLabel20.setText("Course :");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, 30));

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel2.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 630, 170, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 255, 255));
        jLabel21.setText("Note :");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 720, 50, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 1050, 820));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/home.png"))); // NOI18N
        jLabel1.setText("  HOME");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 170, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 290, 80));

        course.setBackground(new java.awt.Color(0, 51, 51));
        course.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        course.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                courseMouseMoved(evt);
            }
        });
        course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                courseMouseExited(evt);
            }
        });
        course.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/edit2.png"))); // NOI18N
        jLabel3.setText(" COURSES");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        course.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 170, 60));

        jPanel1.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 290, 80));

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/smallfee.png"))); // NOI18N
        jLabel4.setText(" FEE STRUCTURE");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 240, 80));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 290, 80));

        jPanel7.setBackground(new java.awt.Color(0, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/view all record.png"))); // NOI18N
        jLabel5.setText("   REPORT");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 210, 80));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 290, 80));

        jPanel9.setBackground(new java.awt.Color(0, 51, 51));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/logout.png"))); // NOI18N
        jLabel23.setText("  LOG OUT");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel23MouseExited(evt);
            }
        });
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 60));

        jPanel10.setBackground(new java.awt.Color(0, 51, 51));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/logout.png"))); // NOI18N
        jLabel22.setText("  LOG OUT");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 60));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 290, 80));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 290, 80));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        print.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fdams/img/printer-.png"))); // NOI18N
        print.setText("  PRINT FEES");
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printMouseExited(evt);
            }
        });
        jPanel4.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 60));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 670, 290, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 820));

        setSize(new java.awt.Dimension(1466, 823));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void wordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wordsActionPerformed

    private void admissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admissionActionPerformed

    private void tuitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuitionActionPerformed

    private void softActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_softActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_softActionPerformed

    private void industrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_industrialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_industrialActionPerformed

    private void universityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_universityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_universityActionPerformed

    private void internalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_internalFocusLost
        // TODO add your handling code here:

        if(isValidate())
        {
            int tot=Integer.parseInt(ad)+Integer.parseInt(tu)+Integer.parseInt(so)+Integer.parseInt(in)+Integer.parseInt(un)+Integer.parseInt(inter);
            total.setText(Integer.toString(tot));
            words.setText(numberSplit(tot,0,0));
        }
    }//GEN-LAST:event_internalFocusLost

    private void internalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internalActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        if(isValidate())
        {
            int tot=Integer.parseInt(ad)+Integer.parseInt(tu)+Integer.parseInt(so)+Integer.parseInt(in)+Integer.parseInt(un)+Integer.parseInt(inter);
            total.setText(Integer.toString(tot));
            words.setText(numberSplit(tot,0,0));
        }
    }//GEN-LAST:event_jPanel2MouseClicked

    boolean isValid(String space) {
     String ePattern = ".*[^ ].*";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(space);
           return m.matches();
   }
    
     boolean isValidNumber(String no) {
     String ePattern = "^[1-9]+[0-9]*$";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(no);
           return m.matches();
   }
    
    String ad,tu,so,in,un,inter;
    
    boolean isValidate()
    {
        ad=admission.getText();
        tu=tuition.getText();
        so=soft.getText();
        in=industrial.getText();
        un=university.getText();
        inter=internal.getText();
    
        if(ad.equals("") || tu.equals("") || so.equals("") || in.equals("") || un.equals("") || inter.equals("") || words.getText().equals("") )
        {
         JOptionPane.showMessageDialog(this,"All fields are required");
         return false;
        }
        else if(!isValid(ad) || !isValid(tu) || !isValid(so) || !isValid(in) ||  !isValid(un) || !isValid(inter))
        {
         JOptionPane.showMessageDialog(this,"Spaces are not allowed!");
         return false;
        } 
        else if(!isValidNumber(ad) || !isValidNumber(tu) || !isValidNumber(so) || !isValidNumber(in) ||  !isValidNumber(un) || !isValidNumber(inter))
        {
         JOptionPane.showMessageDialog(this,"Only digits are allowed!");
         return false;
        }
    
    return true;
    
    }
    
    int tl=0;
    
    void newtotl(int total,String course,int duration,String yr)
    {
        try
        {
         Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/fdams","root","");
        /*String sqli="update course"+i+" set fee=?";
        PreparedStatement stmti;
        stmti = conn.prepareStatement(sqli);
        stmti.executeUpdate();*/
        for(int i=1;i<=duration;i++)
        {
        if(Integer.parseInt(yr)!=i)
        {    
        String sqli="select * from "+course+i;
        PreparedStatement stmti;
        stmti = conn.prepareStatement(sqli);
        ResultSet m=stmti.executeQuery();
        if(m.next())
         tl=tl+m.getInt("amount");
        }
        else 
        {
        tl=tl+total;
        }
        }
        String sql="UPDATE course SET fee=? where courses=?";
        PreparedStatement stmt;
        stmt = conn.prepareStatement(sql);
        stmt.setInt(1,tl);
        stmt.setString(2,course);
        stmt.executeUpdate();
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
            e.printStackTrace();
        }
    }
    
    void updateRecord()
    {
        int adi=Integer.parseInt(admission.getText());
        int tui=Integer.parseInt(tuition.getText());
        int soi=Integer.parseInt(soft.getText());
        int ini=Integer.parseInt(industrial.getText());
        int uni=Integer.parseInt(university.getText());
        int interi=Integer.parseInt(internal.getText());
        int tota=Integer.parseInt(total.getText());

        
        try
       {   
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/fdams","root","");
        String sql="update "+cr+yr+" set addmission_fee=?,tuition_fee=?,soft_skill_fee=?,industrial_training_fee=?,university_fee=?,internal_exam_fee=?,amount=?";
        PreparedStatement stmt;
        stmt = conn.prepareStatement(sql);
        stmt.setInt(1,adi);
        stmt.setInt(2,tui);
        stmt.setInt(3,soi);
        stmt.setInt(4,ini);
        stmt.setInt(5,uni);
        stmt.setInt(6,interi);
        stmt.setInt(7,tota);


        int get=stmt.executeUpdate();
        
        if(get>0)
        {
        JOptionPane.showMessageDialog(this,"Fee Structure has been Updated Successfully!");
        newtotl(tota,cr,drtn,y);
        feesearch f=new feesearch();
        f.show();
        this.dispose();
        }
        else 
        {
        JOptionPane.showMessageDialog(this,"Some technical glitch..try again!");
        }
       }
       catch(HeadlessException | ClassNotFoundException | SQLException e)
       {
           e.printStackTrace();
       }
    
    
    }
    
    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        // TODO add your handling code here:
        
        if(isValidate())
        {
        updateRecord();
        }
    }//GEN-LAST:event_upActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseExited
        // TODO add your handling code here:
        Color col=new Color(0,51,51);
        jPanel1.setBackground(col);
    }//GEN-LAST:event_printMouseExited

    private void printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseEntered
        // TODO add your handling code here:
        Color col=new Color(105,105,105);
        jPanel1.setBackground(col);
        jPanel1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_printMouseEntered

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        // TODO add your handling code here:

        ad=admission.getText();
        tu=tuition.getText();
        so=soft.getText();
        in=industrial.getText();
        un=university.getText();
        inter=internal.getText();
        String tot=total.getText();
        String word=words.getText();
        String note=notes.getText();

        printfee1 pr=new printfee1(ad,tu,so,in,un,inter,tot,word,note,cr,y);
        pr.show();
        this.dispose();

    }//GEN-LAST:event_printMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        studentfeerecord cv=new studentfeerecord();
        cv.show();
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        Color col=new Color(105,105,105);
        jPanel3.setBackground(col);
        jPanel3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        Color col=new Color(0,51,51);
        jPanel3.setBackground(col);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        core1 c=new core1();
        c.show();
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        Color col=new Color(105,105,105);
        course.setBackground(col);
        course.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        Color col=new Color(0,51,51);
        course.setBackground(col);
    }//GEN-LAST:event_jLabel3MouseExited

    private void courseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseMouseMoved
        // TODO add your handling code here:
        course.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        Color col=new Color(105,105,105);
        course.setBackground(col);
    }//GEN-LAST:event_courseMouseMoved

    private void courseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseMouseClicked
        // TODO add your handling code here:
        core cor=new core();
        cor.show();
        this.dispose();
    }//GEN-LAST:event_courseMouseClicked

    private void courseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseMouseExited
        // TODO add your handling code here:
        Color col=new Color(0,51,51);
        course.setBackground(col);
    }//GEN-LAST:event_courseMouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        feesearch1 fs=new feesearch1();
        fs.show();
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        Color col=new Color(105,105,105);
        jPanel6.setBackground(col);
        jPanel6.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        Color col=new Color(0,51,51);
        jPanel6.setBackground(col);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        feerec stu=new feerec();
        stu.show();
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        Color col=new Color(105,105,105);
        jPanel7.setBackground(col);
        jPanel7.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        Color col=new Color(0,51,51);
        jPanel7.setBackground(col);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        login lg=new login();
        lg.show();
        this.dispose();
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseEntered
        // TODO add your handling code here:
        Color col=new Color(105,105,105);
        jPanel9.setBackground(col);
        jPanel9.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel23MouseEntered

    private void jLabel23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseExited
        // TODO add your handling code here:
        Color col=new Color(0,51,51);
        jPanel9.setBackground(col);
    }//GEN-LAST:event_jLabel23MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updaterecord1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updaterecord1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updaterecord1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updaterecord1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updaterecord1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField admission;
    private javax.swing.JPanel course;
    private javax.swing.JTextField industrial;
    private javax.swing.JTextField internal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea notes;
    private javax.swing.JLabel print;
    private javax.swing.JLabel setcourse1;
    private javax.swing.JLabel setduration;
    private javax.swing.JTextField soft;
    private javax.swing.JTextField total;
    private javax.swing.JTextField tuition;
    private javax.swing.JTextField university;
    private javax.swing.JButton up;
    private javax.swing.JTextField words;
    // End of variables declaration//GEN-END:variables
}
